<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mobile_robot">

  <!-- Définition des propriétés pour la taille du robot -->
  <xacro:property name="length" value="0.6"/>
  <xacro:property name="width" value="0.4"/>
  <xacro:property name="height" value="0.2"/>
  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width" value="0.02"/>
  <xacro:property name="lidar_height" value="0.15"/>

  <!-- Définition de la base du robot -->
  <link name="base_link">
    <inertial>
      <mass value="5.0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
    <visual>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
      <material name="green"/>
    </visual>
    <collision>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
    </collision>
  </link>

  <!-- Définition des roues -->
  <xacro:macro name="wheel" params="name x y">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>
    <joint name="${name}_joint" type="revolute">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="10.0" velocity="10.0"/>
    </joint>
  </xacro:macro>

  <!-- Positionnement des roues -->
  <xacro:wheel name="front_left_wheel" x="${length/4}" y="${width/4}"/>
  <xacro:wheel name="front_right_wheel" x="${length/4}" y="${-width/4}"/>
  <xacro:wheel name="rear_left_wheel" x="${-length/4}" y="${width/4}"/>
  <xacro:wheel name="rear_right_wheel" x="${-length/4}" y="${-width/4}"/>

  <!-- Définition du LIDAR -->
  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="0.04" length="0.02"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.04" length="0.02"/>
      </geometry>
    </collision>
  </link>
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${lidar_height}" rpy="0 0 0"/>
  </joint>

  <!-- Définition du capteur LIDAR -->
  <gazebo>
    <sensor name="lidar" type="ray">
      <pose>0 0 ${lidar_height} 0 0 0</pose>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-1.5708</min_angle>
            <max_angle>1.5708</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.12</min>
          <max>12.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
      <plugin name="lidar_plugin" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <namespace>/</namespace>
          <remapping>scan:=/scan</remapping>
        </ros>
      </plugin>
    </sensor>
  </gazebo>

</robot>
